# Generated by Django 3.1.4 on 2021-01-10 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210110_1739'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
