run-server:
	python3 manage.py runserver

migrate:
	python3 manage.py makemigrations
	python3 manage.py migrate

create-app:
	python3 manage.py startapp todo

superuser:
	python3 manage.py createsuperuser
