install-node:
	brew install node

install-node-10:
	brew install node@10

set-node-alias:
	alias node13='export PATH="/usr/local/opt/node@13/bin:$PATH"'
	alias node12='export PATH="/usr/local/opt/node@12/bin:$PATH"'
	alias node10='export PATH="/usr/local/opt/node@10/bin:$PATH"'

switch-node-10:
	node10
