run-server:
	python3 manage.py runserver

migrate:
	python3 manage.py makemigrations
	python3 manage.py migrate

create-app:
	python3 manage.py startapp portfolio

create-blog:
	python3 manage.py startapp blog

superuser:
	python3 manage.py createsuperuser
